pages/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'pages'
app_name = 'store'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

pharmacy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include(('store.urls', 'store'), namespace='store')),
    # path('', include(('distributor.urls', 'distributor'), namespace='distributor'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import *
app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('shop', HomeView.as_view(), name='shop'),
    path('shopsingle/<slug>/', ItemDetailView.as_view(), name= 'shopsingle'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    # path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('search/', views.search, name='search'),
    path('cart/', OrderSummaryView.as_view(), name='cart'),
path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('checkout/', views.checkOut, name='checkout'),
    path('registration/', views.Pharegister, name='registration'),
    path('contact/', views.contact, name='contact'),
    path('thankyou/', views.thankyou, name='thankyou'),

    path('about', views.about, name='about'),
]

templates/_footer.html
 <!-- footer -->
 <div class="site-wrap" style="height:10px;>
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

            <div class="block-7">
              <h3 class="footer-heading mb-4">About Us</h3>
              <p>E-Pharmacy is an innovative pharmacy-led healthcare group. Our mission is to provide integrated pharmacy services with Convenience and Quality. We are reinventing the concept of retail pharmacy by taking authentic medicines to patients’ door-step as quickly as possible.</p>
            </div>

          </div>
          <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
            <h3 class="footer-heading mb-4">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="#">Supplements</a></li>
              <li><a href="#">Vitamins</a></li>
              <li><a href="#">Diet &amp; Nutrition</a></li>
              <li><a href="#">Tea &amp; Coffee</a></li>
            </ul>
          </div>

          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">New ghallah mandi shop #58, Punjab, Khanpur, Pakistan</li>
                <li class="phone"><a href="tel://23923929210">+923017238234</a></li>
                <li class="email">Bilalsharif4@gmail.com</li>
              </ul>
            </div>


          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;
              <script>document.write(new Date().getFullYear());</script> All rights reserved <i class="icon-hart" aria-hidden="true"></i> by <a href="http://www.khanpurland.online/" target="_blank"
                class="text-primary">Bilal Corp</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>

        </div>
      </div>
    </footer>
 </div>

templates/_navbar.html
{% load cart_template_tags %}
<div class="site-wrap">
<div class="site-navbar py-2">

      <div class="search-wrap">
        <div class="container">
          <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
          <form action="#" method="post">
            <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
          </form>
        </div>
      </div>

      <div class="container">
        <div class="d-flex align-items-center justify-content-between">
          <div class="logo">
            <div class="site-logo">
              <a href="index.html" class="js-logo-clone">E-Pharmacy</a>
            </div>
          </div>
          <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
              <ul class="site-menu js-clone-nav d-none d-lg-block">
                <li



                        {% if '/' == request.path %}
                        class="active"
                      {% else %}
                       class=""
                      {%endif%}
                >


                <a href="/">Home</a></li>
                <li
                    {% if 'shop' in request.path %}
                        class="active"
                      {% else %}
                       class=" "
                      {%endif%}
                >
                    <a href="/shop">Store</a></li>
                    <a href="/registration">Distributor</a></li>
<!--                <li class="has-children">-->
<!--                  <a href="#">Dropdown</a>-->
<!--                  <ul class="dropdown">-->
<!--                    <li><a href="#">Supplements</a></li>-->
<!--                    <li class="has-children">-->
<!--                      <a href="#">Vitamins</a>-->
<!--                      <ul class="dropdown">-->
<!--                        <li><a href="#">Supplements</a></li>-->
<!--                        <li><a href="#">Vitamins</a></li>-->
<!--                        <li><a href="#">Diet &amp; Nutrition</a></li>-->
<!--                        <li><a href="#">Tea &amp; Coffee</a></li>-->
<!--                      </ul>-->
<!--                    </li>-->
<!--                    <li><a href="#">Diet &amp; Nutrition</a></li>-->
<!--                    <li><a href="#">Tea &amp; Coffee</a></li>-->

<!--                  </ul>-->
<!--                </li>-->
                <li

                        {% if 'about' in request.path %}
                        class="active"
                      {% else %}
                       class=""
                      {%endif%}



                ><a href="/about">About</a></li>
                <li><a href="/contact">Contact</a></li>
              </ul>
            </nav>
          </div>
          <div class="icons">
            <a href="#" class="icons-btn d-inline-block js-search-open"><span class="icon-search"></span></a>
            <a href="/cart" class="icons-btn d-inline-block bag">
              <span class="icon-shopping-bag"></span>
              <span class="number">{{ request.user|cart_item_count }}</span>
            </a>
            <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none"><span
                class="icon-menu"></span></a>
          </div>
        </div>
      </div>
    </div>
 </div>

templates/about.html
{% extends 'base.html' %}
{%load static %}

{% block content%}
 <div class="site-wrap">
    <div class="site-blocks-cover inner-page" style="background-image: url({% static 'images/hero_1.jpg' %});">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 mx-auto align-self-center">
            <div class=" text-center">
              <h1>About Us</h1>
              <p>E-Pharmacy is an innovative pharmacy-led healthcare group. Our mission is to provide integrated pharmacy services with Convenience and Quality. We are reinventing the concept of retail pharmacy by taking authentic medicines to patients’ door-step as quickly as possible.</p>ˀ
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section bg-light custom-border-bottom" data-aos="fade">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6">
            <div class="block-16">
              <figure>
                <img src="{% static 'images/bg_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
                <a href="https://vimeo.com/channels/staffpicks/93951774" class="play-button popup-vimeo"><span
                    class="icon-play"></span></a>

              </figure>
            </div>
          </div>
          <div class="col-md-1"></div>
          <div class="col-md-5">


            <div class="site-section-heading pt-3 mb-4">
              <h2 class="text-black">How We Started</h2>
            </div>
            <p>...</p>

          </div>
        </div>
      </div>
    </div>



    <div class="site-section bg-light custom-border-bottom" data-aos="fade">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6 order-md-2">
            <div class="block-16">
              <figure>
                <img src="{% static 'images/hero_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
                <a href="https://vimeo.com/channels/staffpicks/93951774" class="play-button popup-vimeo"><span
                    class="icon-play"></span></a>

              </figure>
            </div>
          </div>
          <div class="col-md-5 mr-auto">


            <div class="site-section-heading pt-3 mb-4">
              <h2 class="text-black">We Are Trusted Company</h2>
            </div>
            <p class="text-black">...</p>
            <p class="text-black">...</p>

          </div>
        </div>
      </div>
    </div>

    <div class="site-section site-section-sm site-blocks-1 border-0" data-aos="fade">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
            <div class="icon mr-4 align-self-start">
              <span class="icon-truck text-primary"></span>
            </div>
            <div class="text">
              <h2>Free Shipping</h2>
              <p>...</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
            <div class="icon mr-4 align-self-start">
              <span class="icon-refresh2 text-primary"></span>
            </div>
            <div class="text">
              <h2>Free Returns</h2>
              <p>...</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
            <div class="icon mr-4 align-self-start">
              <span class="icon-help text-primary"></span>
            </div>
            <div class="text">
              <h2>Customer Support</h2>
              <p>...</p>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="site-section bg-light custom-border-bottom" data-aos="fade">
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7 site-section-heading text-center pt-4">
            <h2>The Team</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-lg-6 mb-5">

            <div class="block-38 text-center">
              <div class="block-38-img">
                <div class="block-38-header">
                  <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder" class="mb-4">
                  <h3 class="block-38-heading h4">Maryam</h3>
                  <p class="block-38-subheading">Co-Founder</p>
                </div>
                <div class="block-38-body">
                  <p>
... </p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-6 mb-5">
            <div class="block-38 text-center">
              <div class="block-38-img">
                <div class="block-38-header">
                  <img src="{% static 'images/ceo.jpg' %}" alt="Image placeholder" class="mb-4">
                  <h3 class="block-38-heading h4">Dr. Muhammad Abubakar Siddique</h3>
                  <p class="block-38-subheading"> CEO/Co-Founder</p>
                </div>
                <div class="block-38-body">
                  <p>Ph.D,Chongqing University, Chongqing, P.R China. </p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-6 mb-5">
            <div class="block-38 text-center">
              <div class="block-38-img">
                <div class="block-38-header">
                  <img src="{% static 'images/person_3.jpg' %}" alt="Image placeholder" class="mb-4">
                  <h3 class="block-38-heading h4">Muhammad Bilal</h3>
                  <p class="block-38-subheading">c0-founder<br></br>Marketing</p>
                </div>
                <div class="block-38-body">
                  <p>... </p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-6 mb-5">
            <div class="block-38 text-center">
              <div class="block-38-img">
                <div class="block-38-header">
                  <img src="{% static 'images/person_4.jpg' %}" alt="Image placeholder" class="mb-4">
                  <h3 class="block-38-heading h4">Bilal bal</h3>
                  <p class="block-38-subheading">c0-founder<br></br> Manager</p>
                </div>
                <div class="block-38-body">
                  <p>... </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
 </div>
{%endblock%}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
     <title>E-Phamacy</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">


  <link rel="stylesheet" href="{% static 'css/aos.css' %}">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">



</head>
{% include '_navbar.html' %}
<body>

 <div class="mt-0 pt-0">
    {% if messages %}
        {% for message in messages %}
        <div class=" alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

{% block content%}


{%endblock%}



  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>
{% include '_footer.html' %}
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}


{% block content%}
 <div class="site-wrap">

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0">
            <a href="index.html">Home</a> <span class="mx-2 mb-0">/</span>
            <strong class="text-black">Cart</strong>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <form class="col-md-12" method="post">
            <div class="site-blocks-table">
              <table class="table table-bordered">
                <thead>
                  <tr>

                    <th class="product-thumbnail">Image</th>
                    <th class="product-name">Product</th>
                    <th class="product-price">Price</th>
                    <th class="product-quantity">Quantity</th>
                    <th class="product-total">Total</th>
                    <th class="product-remove">Remove</th>
                  </tr>
                </thead>
                <tbody>
                {% for order_item in object.items.all%}
                  <tr>


                    <td class="product-thumbnail">
                      <img src="{{ order_item.item.image.url }}" alt="Image" class="img-fluid">
                    </td>
                    <td class="product-name">
                      <h2 class="h5 text-black">{{ order_item.item.title }}</h2>
                    </td>
                    <td>{{ order_item.item.price }}</td>

                    <td>
<!--                      <div class="input-group mb-3" style="max-width: 120px;">-->
<!--                        <div class="input-group-prepend">-->
<!--                         -->
<!--                        </div>-->
                         <a href="{% url 'store:remove-single-item-from-cart' order_item.item.slug %}" class="btn btn-outline-primary  "   >&minus;</a>
                               {{ order_item.quantity }}


<!--                        <input type="text" class="form-control text-center" value="1" placeholder=""-->
<!--                          aria-label="Example text with button addon" aria-describedby="button-addon1">-->
                           <a href="{% url 'store:add-to-cart' order_item.item.slug %}" class="btn btn-outline-primary ">&plus;</a>
<!--                        <div class="input-group-append">-->
<!--                         -->
<!--                        </div>-->
<!--                      </div>-->

                    </td>


                    <td>

            {% if order_item.item.discount_price %}
                Rs{{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving rs{{ order_item.get_amount_saved }}</span>
            {% else %}
                Rs{{ order_item.get_total_item_price }}
            {% endif %}

                    </td>
                    <td><a href="{% url 'store:remove-from-cart' order_item.item.slug %}" class="btn btn-primary height-auto btn-sm">X</a></td>
                  </tr>



                    {%endfor%}

                </tbody>
              </table>
            </div>
          </form>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="row mb-5">
              <div class="col-md-6 mb-3 mb-md-0">
              <a class="btn btn-primary btn-lg btn-block" href="/shop">Continue Shopping</a>
              </div>
              <div class="col-md-6">

              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <label class="text-black h4" for="coupon">Coupon</label>
                <p>Enter your coupon code if you have one.</p>
              </div>
              <div class="col-md-8 mb-3 mb-md-0">
                <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
              </div>
              <div class="col-md-4">
                <button class="btn btn-primary btn-md px-4">Apply Coupon</button>
              </div>
            </div>
          </div>
          <div class="col-md-6 pl-5">
            <div class="row justify-content-end">
              <div class="col-md-7">
                <div class="row">
{% if object.get_total %}
                  <div class="col-md-12 text-right border-bottom mb-5">
                    <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="col-md-6">
                    <span class="text-black">Subtotal</span>
                  </div>
                  <div class="col-md-6 text-right">
                    <strong class="text-black">Rs{{ object.get_total }}</strong>
                  </div>
                </div>
                <div class="row mb-5">
                  <div class="col-md-6">
                    <span class="text-black">Total</span>
                  </div>
                  <div class="col-md-6 text-right">
                    <strong class="text-black">Rs{{ object.get_total }}</strong>
                  </div>
                </div>
{%endif%}
                <div class="row">
                  <div class="col-md-12">
                    <a class="btn btn-primary btn-lg btn-block" href="/checkout">Proceed To
                      Checkout</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


        <div class="site-section bg-secondary bg-image" style="background-image: url({% static 'images/bg_2.jpg' %});">
      <div class="container">
        <div class="row align-items-stretch">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a href="#" class="banner-1 h-100 d-flex" style="background-image: url({% static 'images/bg_1.jpg' %});">
              <div class="banner-1-inner align-self-center">
                <h2>E-Pharmacy Products</h2>
                <p>E-Pharmacy is a pharmacy with a difference. Only qualified pharmacists handle all our pharmaceutical products, including procurement, storage, and dispensing.
                </p>
              </div>
            </a>
          </div>
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a href="#" class="banner-1 h-100 d-flex" style="background-image: url({% static 'images/bg_2.jpg' %});">
              <div class="banner-1-inner ml-auto  align-self-center">
                <h2>Rated by Experts</h2>
                  <p>Our trusted hospital and laboratory partners include: <strong> <b>sheikh zayed hospital rahim yar khan</b></strong>
                </p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
 </div>
{%endblock%}

templates/formpage.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap 3 Contact Form - reusable form</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" >
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <link rel="stylesheet" href="form.css" >
        <script src="form.js"></script>
    </head>
    <body >
        <div class="container">
            <div class="row">
                <div class="col-md-6 " id="form_container">
                    <h2>Contact Us</h2> 
                    <p> Please send your message below. We will get back to you at the earliest! </p>
                    <form role="form" method="post" id="reused_form">
                        <div class="row">
                            <div class="col-sm-12 form-group">
                                <label for="message"> Message:</label>
                                <textarea class="form-control" type="textarea" id="message" name="message" maxlength="6000" rows="7"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 form-group">
                                <label for="name"> Your Name:</label>
                                <input type="text" class="form-control" id="name" name="name" required>
                            </div>
                            <div class="col-sm-6 form-group">
                                <label for="email"> Email:</label>
                                <input type="email" class="form-control" id="email" name="email" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 form-group">
                                <button type="submit" class="btn btn-lg btn-default pull-right" >Send &rarr;</button>
                            </div>
                        </div>
                    </form>
                    <div id="success_message" style="width:100%; height:100%; display:none; "> <h3>Posted your message successfully!</h3> </div>
                    <div id="error_message" style="width:100%; height:100%; display:none; "> <h3>Error</h3> Sorry there was an error sending your form. </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/registration.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fontss/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'csss/style.css' %}">
</head>
<body>

    <div class="main">

        <section class="signup">
            <img src="{% static 'imagess/signup-bg.jpg' }" alt="">
            <div class="container">
                <div class="signup-content">
                    <form method="POST" id="signup-form" class="signup-form" action="">
                        {% csrf_token %}
                        <h2 class="form-title">Register your pharmacy</h2>
                        <div class="form-group">
                            <input type="text" class="form-input" name="name" id="firstname" placeholder="First name"/>
                        </div>
                         <div class="form-group">
                            <input type="text" class="form-input" name="name" id="lastname" placeholder="Last name"/>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-input" name="email" id="email" placeholder="Your Email"/>
                        </div>
                         <div class="form-group">
                            <input type="text" class="form-input" name="name" id="contact" placeholder="Contact number"/>
                        </div>
                         <div class="form-group">
                            <input type="text" class="form-input" name="name" id="cnic" placeholder="CNIC"/>
                        </div>
                         <div class="form-group">
                            <input type="text" class="form-input" name="name" id="address" placeholder="Address"/>
                        </div>
                         <div class="form-group">
                            <input type="text" class="form-input" name="name" id="licence" placeholder="Licence number"/>
                        </div>
                         <div class="form-group">
                            <input type="text" class="form-input" name="name" id="brand" placeholder="Brand"/>
                        </div>

                        <div class="form-group">
                            <input type="text" class="form-input" name="password" id="password" placeholder="Password"/>
                            <span toggle="#password" class="zmdi zmdi-eye field-icon toggle-password"></span>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-input" name="re_password" id="password2" placeholder="Repeat your password"/>
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                            <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="Sign up"/>
                        </div>
                    </form>
<!--                    <p class="loginhere">-->
<!--                        Have already an account ? <a href="#" class="loginhere-link">Login here</a>-->
<!--                    </p>-->
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'vendorr/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'jss/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/search.html
{% extends 'base.html' %}
{% load static %}


{% block content%}
{%endblock%}

templates/thankyou.html
{% extends 'base.html' %}
{% load static %}


{% block content%}
 <div class="site-wrap">

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong
              class="text-black">Thank You</strong></div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <span class="icon-check_circle display-3 text-success"></span>
            <h2 class="display-3 text-black">Thank you!</h2>
            <p class="lead mb-5">You order was successfuly completed.</p>
            <p><a href="shop.html" class="btn btn-md height-auto px-4 py-3 btn-primary">Back to store</a></p>
          </div>
        </div>
      </div>
    </div>
 </div>
{%endblock%}